### ISSUE TITLE
Improved documentation & examples 

### ISSUE THREAD

**Issue by sebastianmacias** [go-reform/reform#105]
It would help new comers to provide a more complete documentation like http://jinzhu.me/gorm/ with additional examples besides what is in the godoc.org and README pages.

**Comment by AlekSi** [comment]
Absolutely. See #8.

Do you have some specific questions?

**Comment by AlekSi** [comment]
Closing as a duplicate of #8.

Feel free to ask specific questions there or comment on #8.
