### ISSUE TITLE
Support for nested structs?

### ISSUE THREAD

**Issue by anton-107** [go-reform/reform#12]
It will be nice if reform could map nested structs to a single table.
Example:

``` go
type DateTime struct {
    Date time.Time `reform: date`
    Timezone string `reform: timezone`
}

// reform:events
type Event struct {
    Start DateTime `reform: start_`
    End DateTime `reform: end_`
}
```

And that would map to a table with `start_date`, `start_timezone`, `end_date` and `end_timezone` columns.

**Comment by AlekSi** [comment]
That's definitely planned, two alternative syntaxes are being considered. I will post more details soon.

**Comment by AlekSi** [comment]
Ok, that syntax is _not_ going to be implemented. Nested structures will be used for JOINs (#54).
