### ISSUE TITLE
Why is `ErrNoRows` thrown if no rows were updated?

### ISSUE THREAD

**Issue by seenickcode** [go-reform/reform#122]
Hello, referring to this piece of code:

```
// Update updates all columns of row specified by primary key in SQL database table with given record.
// If record implements BeforeUpdater, it calls BeforeUpdate() before doing so.
//
// Method returns ErrNoRows if no rows were updated.
// Method returns ErrNoPK if primary key is not set.
func (q *Querier) Update(record Record) error {
	err := q.beforeUpdate(record)
	if err != nil {
		return err
	}

	table := record.Table()
	values := record.Values()
	columns := table.Columns()

	// cut primary key
	pk := table.PKColumnIndex()
	values = append(values[:pk], values[pk+1:]...)
	columns = append(columns[:pk], columns[pk+1:]...)

	return q.update(record, columns, values)
}
```

Why `Method returns ErrNoRows if no rows were updated.` ?   Why is this an error? Users may sometimes want to update something regardless if no changes were made to a row.  Errors should be thrown only if they are unexpected, no?

**Comment by AlekSi** [comment]
In Go errors are not exceptions, they are totally expected. They are being returned, not thrown.

There are two reasons for ErrNoRows:
1. In my experience, not being to update a row by a primary is more often an error than not. I just checked the large proprietary code that uses reform. We have a lot of calls to Update there, but only a few checks for ErrNoRows. So that's just an optimization for a more common case (for us).
2. For consistency with other methods that work with primary keys: FindByPrimaryKeyFrom, Delete, etc.

**Comment by seenickcode** [comment]
Hey @AlekSi , thanks for the quick reply.  

As a user, when I see the only value returned from an Update function is `error`, I expect that the database transaction failed.  In this case, it succeeded but still gives me an error.

Therefore, how can I differentiate between a "real" error thrown by SQL (i.e. a DB constraint wasn't met) and this "no rows were updated" error?  The only way I know is to compare the strings i.e. `err.Error() == "sql: no rows updated..."`

What about returning an int of the amount of rows that were actually updated (in this case 0?) and treat errors as only when a transaction fails?

**Comment by AlekSi** [comment]
You should compare value directly:
```go
err := q.Update(&user)
if err == reform.ErrNoRows {
  err = nil  // that's fine if user not found
}
if err != nil {
  return err
}
```

**Comment by seenickcode** [comment]
Hey that makes sense to wait until v2.

In the meantime though, I think you might want to mention how Update will send an error even if the update worked if no rows were updated as this is a critical trip-up for folks (me, my dev team member both got super confused).

Lastly, FYI I tried this and it looks like one must do instead:

`err.Error() == reform.ErrNoRows.Error()`
