### ISSUE TITLE
We need Examples

### ISSUE THREAD

**Issue by EagleMoor** [go-reform/reform#15]
Нужно как можно больше примеров. Хотя бы с инициализацией DB.

Столкнулся с проблемой при создании `reform.NewDB`, а именно с `Logger`.
Стандартный `Logger` я использовать не могу, `Logger` который interface тоже, а `PrintfLogger`, который сам напрашивается для использования, тоже не могу применить, тк не знаю кто поддерживает `type Printf func(format string, a ...interface{})`

Если бы пример на главной странице был более подробный, с открытием `database/sql` соединения, созданием логера и использовании — это очень сильно помогло бы разобраться что да как.

**Comment by AlekSi** [comment]
> не знаю кто поддерживает type Printf func(format string, a ...interface{})
That's documented: https://godoc.org/github.com/AlekSi/reform#Printf

Other points are valid though.

**Comment by AlekSi** [comment]
In short:
```go
reform.NewPrintfLogger(log.New(os.Stderr, "reform: ", log.Flags()).Printf)
```

**Comment by EagleMoor** [comment]
Not work for good Logger interface

```go
var Log *reform.PrintfLogger
​
Log = reform.NewPrintfLogger(log.New(os.Stderr, "gnss: ", log.Flags()).Printf)
DB = reform.NewDB(db, postgresql.Dialect, Log)
```
and Log don't have Logger interface and methods

**Comment by AlekSi** [comment]
```go
db := reform.NewDB(conn, postgresql.Dialect, reform.NewPrintfLogger(log.New(os.Stderr, "SQL: ", 0).Printf))
```
That line from our project defintely works.

**Comment by EagleMoor** [comment]
example for use global logger

`
var Log *log.Logger
...

// init
Log = log.New(os.Stderr, "SQL: ", log.Flags())
DB = reform.NewDB(db, postgresql.Dialect, reform.NewPrintfLogger(Log.Printf))
`

it's work =)

**Comment by AlekSi** [comment]
Added in 42849de1e33792b6b63911479876e6a56e174432.
