### ISSUE TITLE
Update to latest changes in github.com/denisenkom/go-mssqldb

### ISSUE THREAD

**Issue by AlekSi** [go-reform/reform#151]
github.com/denisenkom/go-mssqldb [recently implemented](https://github.com/denisenkom/go-mssqldb/commits/master) [`database/sql/driver.SessionResetter` interface](https://golang.org/pkg/database/sql/driver/#SessionResetter) which broke our tests due to `SET IDENTITY_INSERT` used by them.

**Comment by AlekSi** [comment]
@AlekseyMartynov May you take a look, please?

**Comment by AlekseyMartynov** [comment]
From debugging I understand that with `SessionResetter`, `SET IDENTITY_INSERT` must be called in each transaction (or even before each query?)

To satisfy this in tests, `setIdentityInsert` can be called immediately before and after `Insert`:

```
setIdentityInsert(s.T(), tx.Querier, "people", true)
s.NoError(tx.Insert(person))
setIdentityInsert(s.T(), tx.Querier, "people", false)
```

`reform-db` is more tricky. Specifically for test data in `internal/test/sql`, a possible solution is to combine all SQL in a single temporary file.

Interesting insight is that using one connection doesn't solve all problems:

https://github.com/go-reform/reform/blob/161dee950cbd38085dac33c87ef81140f2da99cc/reform-db/main.go#L56-L59
