### ISSUE TITLE
Support Go modules

### ISSUE THREAD

**Issue by rumyantseva** [go-reform/reform#170]
As [Go Modules](https://github.com/golang/go/wiki/Modules) are going to be presented as a part of Go 1.11, it might make sense to start supporting them.

**Comment by bikbah** [comment]
duplicate of #161 ?

**Comment by AlekSi** [comment]
Indeed! Thanks.

**Comment by dgellow** [comment]
Any update on this issue? As far as I can tell @rumyantseva's PR solved the issue, but is now outdated.

**Comment by AlekSi** [comment]
Done at #211.
