### ISSUE TITLE
`reform-db init` should not stop on errors

### ISSUE THREAD

**Issue by ghost** [go-reform/reform#174]
This is kind of feature request or propose. It would be nice if reform would have exclude flag in command line, for example i have tables for another app which have composite primary key, and they're not needed in my Go application at all.

**Comment by AlekSi** [comment]
Are you talking about `reform` or `reform-db` tool? How you invoke it?

**Comment by PavelLJ** [comment]
@AlekSi I was talking about reform-db generate-from-schema tool.

**Comment by AlekSi** [comment]
Normally, you should invoke `reform-db` only once, then remove extra files and edit what you need. Then you should invoke `reform` and add all files into the repository.
I'm not sure why a flag is needed in that case. Please explain.

**Comment by PavelLJ** [comment]
I mean, i have a tables which are not supported by reform at the moment (composite primary key for .net core auth), and because of this my generation halts

**Comment by AlekSi** [comment]
Ok, got it, that the problem.

**Comment by AlekSi** [comment]
Looking into https://github.com/go-reform/reform/blob/v1-4/reform-db/cmd_init.go, I don't really see a place where this error is not handled gracefully (i.e. logged and skipped). What is the error output?

**Comment by PavelLJ** [comment]
`reform-db: Expected single column primary key, got 2`
But I'm using v.1.3.2

**Comment by AlekSi** [comment]
Ok, it's there: https://github.com/go-reform/reform/blob/v1-4/reform-db/cmd_init.go#L110 I think we should log this error, but not fail. Please send a pull request. :)

**Comment by PavelLJ** [comment]
This may sound very foolish, but i can't :D. As i already said earlier, I'm newbie in Go, so i may do an error in very basic stuff. It would be better if you would commit that. Thank you for being very fast and responsive, I'm really appreciate you help.

**Comment by eschizoid** [comment]
@AlekSi Any idea when is this going to be released?

**Comment by AlekSi** [comment]
The current plan is to release v1.4 at the end of November: https://github.com/go-reform/reform/milestone/8 (note that many issues probably will be pushed out to the next release). In the meantime you can use `v1-4` branch, it should be stable.

**Comment by AlekSi** [comment]
v1.4.0-beta1 is out.
