### ISSUE TITLE
Feature request: generate models for views, not only for tables

### ISSUE THREAD

**Issue by fpawel** [go-reform/reform#181]
### General description of the problem
Reform does not generate models for views in existing database schema, only for tables.

### Code snippets to reproduce the problem described above
I have sample sqlite db in `db.sqlite3`, wich was cretated like this:
```
CREATE TABLE IF NOT EXISTS the_table(  the_filed INTEGER );
CREATE VIEW IF NOT EXISTS the_view AS  SELECT * FROM the_table;
```
I generate a code with reform: `reform-db -db-driver=sqlite3 -db-source=db.sqlite3 init`
reform creates one go file `the_table.go` for table `the_table` :
```
// TheTable represents a row in the_table table.
//reform:the_table
type TheTable struct {
	TheFiled *int64 `reform:"the_filed"`
}
```
But I expect also `the_view.go`  for view `the_view` with following content:
```
// TheView represents a row in the_view view.
//reform:the_view
type TheView struct {
	TheFiled *int64 `reform:"the_filed"`
}
```
I also tried v1-4 branch, the result was the same.

**Comment by AlekSi** [comment]
It is likely that the change is a simple one: we need to add another type [there](https://github.com/go-reform/reform/blob/v1-4/reform-db/cmd_init_sqlite3.go#L64). Want to send a PR?

**Comment by eschizoid** [comment]
great, I was also waiting for this one :)

**Comment by AlekSi** [comment]
Merged into `v1-4`.
