### ISSUE TITLE
Multi insert

### ISSUE THREAD

**Issue by EagleMoor** [go-reform/reform#20]
I think it's a good idea for orm have a method for Insert array struct?

example

```go
DB.Insert(s []Struct)

// SQL
INSERT INTO `table name` (`col1`, `col2`, `col3`) VALUES (s1.col1, s1.col2, s1.col3), (...)
```

If need, i can write It

**Comment by AlekSi** [comment]
More like `DB.Insert(s ...Struct)`.

**Comment by EagleMoor** [comment]
Need splitting into segments? For control how many rows insert by one query? 

```go
DB.Insert(1000, MyStructs)

Transaction begin
Insert MyStructs[0:999]
Insert MyStructs[1000:1900]
Transaction commit
```

or reserve on the side of developers?

**Comment by AlekSi** [comment]
No batch size as argument, no transaction. Just single `INSERT` into the database with all structs.

**Comment by EagleMoor** [comment]
Hm, `s ...Struct` not help for prepare same slice or array and insert all data in one query.

Spesial https://play.golang.org/p/-r6yWGKxne

**Comment by EagleMoor** [comment]
i can write `DB.InsertAll(str []interface{})` method with dynamic check type

**Comment by EagleMoor** [comment]
Oh, yanzay help me. Work like a  https://play.golang.org/p/ofKxGgXCel

**Comment by AlekSi** [comment]
```bash
go get -u gopkg.in/reform.v1
cd $GOPATH/gopkg.in/reform.v1
git checkout origin/multi-insert
```

Please not that PKs are not set back to the records.

**Comment by EagleMoor** [comment]
i think it will be in one function. if not we can write binding before insert
