### ISSUE TITLE
Release a patch version 1.3.4 to remove use of syreclabs.com/go/faker

### ISSUE THREAD

**Issue by dgellow** [go-reform/reform#206]
Hi @AlekSi,

Would it be possible to create a tag v1.3.4 to fix issues with syreclabs.com/go/faker?
I see that the library has been replaced by github.com/brianvoe/gofakeit with the PR https://github.com/go-reform/reform/pull/195 but that hasn't been released yet, thus isn't available through `go get -u gpkg.in/reform.v1`.

For references, issues with syreclabs.com/go/faker:
- https://github.com/go-reform/reform/issues/194
- https://github.com/dmgk/faker/issues/14

```
$ go mod download
#... more fetches
go: finding gopkg.in/reform.v1 v1.3.3
go: syreclabs.com/go/faker@v1.2.0: unrecognized import path "syreclabs.com/go/faker" (https fetch: Get https://syreclabs.com/go/faker?go-get=1: x509: certificate signed by unknown authority)
# ... more fetches
go: error loading module requirements
##[error]Process completed with exit code 1.
```

**Comment by AlekSi** [comment]
v1.3.4 is out. Sorry for delay.
