### ISSUE TITLE
Support of composite primary keys

### ISSUE THREAD

**Issue by xaionaro** [go-reform/reform#25]
When I'm trying to define a composite Primary Key
```
//reform:raw_records
type RawRecord struct {
        ModelBase

        Date           time.Time `reform:"date,pk"`
        SensorId       int       `reform:"sensor_id,pk"`
        ChannelId      int       `reform:"channel_id,pk"`
        Value          int       `reform:"value"`
        ConvertedValue int       `reform:"converted_value"`
}
```
it returns an error:

```
reform: . RawRecord.go: reform: RawRecord has field SensorId with with duplicate "pk" label in "reform:" tag (first used by Date), it is not allowed
```

Seems the feature is not implemented, yet. But if I don't set any PK then reform thinks it's just a view (not a table). So I have to make an extra auto-increment field to use this model by reform.

This issue is just about "please implement support of composite Primary Keys" :)

**Comment by AlekSi** [comment]
That's basically impossible due to the way [database/sql.Result.LastInsertId](https://golang.org/pkg/database/sql/#Result) works.

What are you trying to do that doesn't work with `reform.View`?

**Comment by xaionaro** [comment]
> What are you trying to do that doesn't work with reform.View?

Well, at the moment everything works good. But I suppose "Tables" and "Views" are different entities in `reform` (with different possibilities) and I'll face with some problems in future. Or I'm wrong?

> That's basically impossible due to the way database/sql.Result.LastInsertId works.

I see, thanks. I'll just add an auto-increment field.

Anyway for me the issue has been exhausted, so we can close it.

… Sorry for my English.

**Comment by AlekSi** [comment]
There are several methods that accept `Table` or `Record` as opposed to `View` or `Struct`:
* [FindByPrimaryKeyFrom](https://godoc.org/gopkg.in/reform.v1#Querier.FindByPrimaryKeyFrom)
* [Querier.FindByPrimaryKeyTo](https://godoc.org/gopkg.in/reform.v1#Querier.FindByPrimaryKeyTo)
* [Delete](https://godoc.org/gopkg.in/reform.v1#Querier.Delete)
* [Reload](https://godoc.org/gopkg.in/reform.v1#Querier.Reload)
* [Save](https://godoc.org/gopkg.in/reform.v1#Querier.Save)
* [Update](https://godoc.org/gopkg.in/reform.v1#Querier.Update)
* [UpdateColumns](https://godoc.org/gopkg.in/reform.v1#Querier.UpdateColumns)

All other methods, including `Insert`, work with views.

But yeah, in almost all cases having a surrogate primary key is much better than composite. You should use unique index for (date, sensor_id, channel_id).

**Comment by xaionaro** [comment]
Thank you for your project. I used GORM before it and Reform is much nicer in my subjective perception.
