### ISSUE TITLE
Blacklist and Whitelist functionality for Update and Insert

### ISSUE THREAD

**Issue by m0sth8** [go-reform/reform#30]
What I want for Insert or Update is to take default values from database if it's possible.

```
db.Update(obj, WithBlacklist("id", "created"))
db.Insert(obj, WithWhitelist("name", "surname"))
```

**Comment by EagleMoor** [comment]
Refresh don't help ?

**Comment by m0sth8** [comment]
How should it help?

**Comment by xaionaro** [comment]
I see function UpdateColumns. Is that what are you looking for?

https://godoc.org/gopkg.in/reform.v1#Querier.UpdateColumns

**Comment by AlekSi** [comment]
See #39.

**Comment by AlekSi** [comment]
Probably tests should be improved.

**Comment by xaionaro** [comment]
@AlekSi, how?

**Comment by AlekSi** [comment]
That's mostly for myself, for better understanding of the code I will maintain. I will do it.
