### ISSUE TITLE
Add tag support for sql

### ISSUE THREAD

**Issue by m0sth8** [go-reform/reform#31]
Usually, it's very useful to mark queries with some tags.

This code  `db.Tag("disable_user:%s", userId).Update(user)` might produce the next query `UPDATE /* disable_user:10 */ ...`

**Comment by AlekSi** [comment]
Do you have any examples in existing ORMs?

**Comment by AlekSi** [comment]
Also, you can do it yourself:
```go
func TagQuerier(q *reform.Querier, format string, a ...interface{}) *reform.Querier {
  // copy Querier
  // change logger
  // return
}
```

Or you can create Querier or DB per API request with request-specific logger.

**Comment by AlekSi** [comment]
@m0sth8 shared some details privately. Idea is to generate SQL statements with embedded comments, so it is possible to track them from RDMS logs back to application code. Sounds like a useful feature.
