### ISSUE TITLE
Handle database schema generation and migration

### ISSUE THREAD

**Issue by genez** [go-reform/reform#49]
A similar feature is offered by [gorm](https://github.com/jinzhu/gorm)

**Comment by AlekSi** [comment]
I can see how auto-migrations can be useful.

**Comment by AlekSi** [comment]
@rumyantseva

**Comment by AlekSi** [comment]
I will close this issue in favor of the [Migrations project](https://github.com/go-reform/reform/projects/2). We plan it for 1.4.
