### ISSUE TITLE
Update with tail

### ISSUE THREAD

**Issue by empirefox** [go-reform/reform#50]
Some models can be updated with additional conditions, ie when I about to update OrderTable, I need to ensure the owner with user_id. For now I must do query first to ensure the owner.

**Comment by xaionaro** [comment]
I didn't get it. Can you add examples (of what do you want)?

I'm not a developer of reform, so you can just ignore my question :)

**Comment by empirefox** [comment]
OK, this is what i want to do :)
```go
//reform:cc_order
type UserOrder struct {
	ID     uint `reform:"id,pk"`
	UserID uint `reform:"user_id" json:"-"`

	Contact        string `reform:"contact"`
	Phone          string `reform:"phone"`
	DeliverAddress string `reform:"deliver_addr"`
}
```
user 111 post data to modify order contact:
```json5
{
  ID: 1,
  Contact: "Another",
}
```
then I want to do something like this:
```sql
UPDATE cc_order SET contact = 'Another' WHERE id=1 AND user_id=111
```
Thanks!

**Comment by AlekSi** [comment]
Something like this?
```go
// UpdateView updates specified columns of rows specified by tail and args in SQL database table with given struct,
// and returns a number of updated rows.
// Other columns are omitted from generated UPDATE statement.
// If struct implements BeforeUpdater, it calls BeforeUpdate() before doing so.
//
// Method never returns ErrNoRows.
func (q *Querier) UpdateView(str Struct, columns []string, tail string, args ...interface{}) (uint, error)
```

**Comment by jirfag** [comment]
interface like [this](https://github.com/jirfag/go-queryset#update-multiple-record-or-without-model-object) will be more safe

**Comment by AlekSi** [comment]
Reform is not a query builder, it does not abstract SQL for non-trivial cases – simply because I consider SQL to be more powerful, expressive and simple than any DSL for it. Instead, reform provides helpers for the most common operations (so one does not have to write them over and over again) and building blocks for making your own.
