### ISSUE TITLE
Use go/format when -gofmt=false

### ISSUE THREAD

**Issue by AlekSi** [go-reform/reform#65]
Invoking an external `gofmt` command is relatively slow on Windows. Let's use `go/format` and do formatting ourselves when `-gofmt=false`. We should continue using `gofmt -s` by default because `-s` simplifies our generated code, and it is not possible yet to do it with `go/format`.

**Comment by joaodrp** [comment]
I’ll take this. Do you have any preference on `format` vs `imports`? I can see that you mentioned the need for `imports` in issue [#43](https://github.com/go-reform/reform/issues/43), so maybe that’s the best option (as it’ll also format the code).

**Comment by AlekSi** [comment]
@joaodrp Hi. I updated a title and description. I don't want to rely on the external tool while it is possible, so let's stick with `go/format` for now. And thank you.
