### ISSUE TITLE
How to get sql.DB from reform.DB?

### ISSUE THREAD

**Issue by ababo** [go-reform/reform#98]
I have a helper function which returns `reform.DB`. Is there a way to defer closing of internal `sql.DB` in a calling function which only gets `reform.DB`? I didn't find a way to get a pointer to `sql.DB` from `reform.DB` (please correct me if there is).

**Comment by AlekSi** [comment]
Currently, there is no such method, so you have to pass `*sql.DB` along. I may add one returning `reform.DBInterface` which you can then assert to `*sql.DB`:

```go
func Foo(db *reform.DB) {
  defer db.DBInterface().(*sql.DB).Close()
}
```

But why you want to close database connection in a function which doesn't create it?

**Comment by ababo** [comment]
```golang
// in different package
func Open(foo *Bar) (/*sql.DB,*/*reform.DB, error) {
	// some simple but non-trivial logic
	// returning sql.DB seems to be redundant
	// since reform.DB already contains it.
}

func main() {
	foo := NewBar()
	db, err := Open(foo)
	if err != nil {
		panic("aaaaaaa")
	}
	// need defer db.Close() or db.DB.Close()
	// the second way is preferred since there
	// can be a third-party code which demands sql.DB
}

**Comment by AlekSi** [comment]
Ok, so your database selection function is not trivial by itself.

**Comment by ababo** [comment]
I mean why not to export `reform.db` (as `reform.DB`).

**Comment by AlekSi** [comment]
> I mean why not to export reform.db (as reform.DB).

I don't think I like the exported field here – chaos will break if it's changed when a transaction is open, for example. I like DB to be "hardwired" to particular `*sql.DB`. `DB()` method is fine, though.

Marking it as `help wanted` because this change is simple and self-contained enough for a new contributor. Feel free to send a PR. :)

**Comment by AlekSi** [comment]
@ababo Will you send a Pull Request? Can I help you with it?
